#!/usr/bin/env python3

''' MAPACHE: A Maluable-Architecture Processor, Assembler, and Console Hardware Emulation System. '''

import argparse
from console import MapacheConsole

parser = argparse.ArgumentParser(description="Maluable processor emulation system")
parser.add_argument('asm', nargs='?', help='A ".asm" file to load and run')
parser.add_argument('-q', '--quiet', action='store_true')
args = parser.parse_args()

if __name__ == '__main__':
    verbose = not args.quiet
    console = MapacheConsole(verbose)
    if args.asm:
        console.do_load(args.asm)
        console.do_run('')
    else:
        console.cmdloop()
